### ISSUE TITLE
Run QC manually on bams

### ISSUE THREAD

**Issue by rcurrie** [UCSC-Treehouse/operations#10]
Run docker hbeale/treehouse_bam_qc:1.0 on

EGAD00001001620_ICGC_MB12.sorted.bam
EGAD00001001944_ICGC_GBM5_RNA-seq.sorted.bam
EGAD00001001620_ICGC_MB90.sorted.bam

from:

/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/bams/

**Comment by rcurrie** [comment]
@cygao Started processing all three, one per pipeline0-2

@hbeale any guess as to how many we could do on the same machine? Looks like it isn't really that much and we could run several on a single pipeline class machine?

**Comment by rcurrie** [comment]
@hbeale Errors: I tried running launching into /bin/sh to verify the file in /data was there and it was. Will try again tomorrow morning:

ubuntu@pipeline0:/mnt/qc$ docker run -it --rm -v `pwd`/EGAD00001001620_ICGC_MB12:/data hbeale/treehouse_bam_qc:1.0
runQC.sh





sambamba-sort: Error reading BGZF block starting from offset 3024881618: stream error: not enough data in stream
samblaster: Version 0.1.22
samblaster: Inputting from stdin
samblaster: Outputting to stdout
sambamba-view: Cannot open or create file '/data/rnaAligned.sortedByName.bam' : No such file or directory
samblaster: Missing header on input sam file.  Exiting.

Writing sorted chunks to temporary directory...
[==============================================================================]
@ 2016-10-18 05:53:07: Read BED file (reference gene model) ...
@ 2016-10-18 05:53:26: Total 92523 transcripts loaded
@ 2016-10-18 05:53:26: Get BAM file(s) ...
        /data/rnaAligned.sortedByCoord.md.bam
@ 2016-10-18 05:53:26: Processing rnaAligned.sortedByCoord.md.bam ...
Traceback (most recent call last):
  File "/usr/local/bin/geneBody_coverage.py", line 302, in <module>
    main()
  File "/usr/local/bin/geneBody_coverage.py", line 262, in main
    cvg = genebody_coverage(bamfile, gene_percentiles)
  File "/usr/local/bin/geneBody_coverage.py", line 132, in genebody_coverage
    samfile = pysam.Samfile(bam, "rb")
  File "pysam/calignmentfile.pyx", line 341, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4933)
  File "pysam/calignmentfile.pyx", line 590, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7693)
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
processing /ref/hg38_GENCODE_v23.bed ...^[
 Done
Traceback (most recent call last):
  File "/usr/local/bin/read_distribution.py", line 303, in <module>
    main()
  File "/usr/local/bin/read_distribution.py", line 209, in main
    obj = SAM.ParseBAM(options.input_file)
  File "/usr/local/lib/python2.7/dist-packages/qcmodule/SAM.py", line 2319, in __init__
    self.samfile = pysam.Samfile(inputFile,'r')
  File "pysam/calignmentfile.pyx", line 341, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4933)
  File "pysam/calignmentfile.pyx", line 590, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7693)
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
[1] "analyzing /data/readDist.txt"

**Comment by rcurrie** [comment]
Looks like first one has problematic data, moving on to second:

File: EGAD00001001620_ICGC_MB12.sorted.bam

root@51b90b9239b0:/# sambamba sort --tmpdir /data -t 4 --sort-by-name --out  /data/rnaAligned.sortedByName.bam /data/rnaAligned.sortedBy
sambamba-sort: Cannot open or create file '/data/rnaAligned.sortedBy' : No such file or directory
root@51b90b9239b0:/# Coord.out.bam^C
root@51b90b9239b0:/# sambamba sort --tmpdir /data -t 4 --sort-by-name --out  /data/rnaAligned.sortedByName.bam /data/rnaAligned.sortedByCoord.out.bam
sambamba-sort: Error reading BGZF block starting from offset 3024881618: stream error: not enough data in stream
root@51b90b9239b0:/#

**Comment by rcurrie** [comment]
I'm thinking the script, or data has a bug, second file has same issue (I'm running docker but into /bin/bash and then running the first line of the shell script to debug. Looks like the data is there find):

root@0adee531158f:/# sambamba sort --tmpdir /data -t 4 --sort-by-name --out  /data/rnaAligned.sortedByName.bam /data/rnaAligned.sortedByCoord.out.bam
sambamba-sort: Error reading BGZF block starting from offset 1453477786: stream error: not enough data in stream
root@0adee531158f:/# ls -al /data/
total 1419432
drwxrwxr-x  3 1000 1000       4096 Oct 18 16:24 .
drwxr-xr-x 53 root root       4096 Oct 18 16:23 ..
-rwxrwxr-x  1 1000 1000 1453481984 Oct 18 16:22 rnaAligned.sortedByCoord.out.bam
drwxr-xr-x  2 root root       4096 Oct 18 16:25 sambamba-pid18-pkbp

**Comment by hbeale** [comment]
Luckily (?) the approach of analyzing the smallest files first targeted the
ones that had format problems. I've screened all bams for the issue and I'm
making a request to Jeltje to see if she can fix it (she's been able to
before).


Details:

for i in *.bam ; do echo -n $i; samtools view -h $i | head -1 ; done 2>&1 |
grep '\['
EGAD00001001620_ICGC_MB110.sorted.bam[bam_header_read] EOF marker is
absent. The input is probably truncated.
EGAD00001001620_ICGC_MB113.sorted.bam[bam_header_read] EOF marker is
absent. The input is probably truncated.
EGAD00001001620_ICGC_MB12.sorted.bam[bam_header_read] EOF marker is absent.
The input is probably truncated.
EGAD00001001620_ICGC_MB90.sorted.bam[bam_header_read] EOF marker is absent.
The input is probably truncated.
EGAD00001001620_ICGC_MB95.sorted.bam[bam_header_read] EOF marker is absent.
The input is probably truncated.
EGAD00001001944_ICGC_GBM1_RNA-seq.sorted.bam[bam_header_read] EOF marker is
absent. The input is probably truncated.
EGAD00001001944_ICGC_GBM2_RNA-seq.sorted.bam[bam_header_read] EOF marker is
absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from
"EGAD00001001944_ICGC_GBM2_RNA-seq.sorted.bam".
EGAD00001001944_ICGC_GBM5_RNA-seq.sorted.bam[bam_header_read] EOF marker is
absent. The input is probably truncated.
EGAD00001001944_ICGC_GBM6_RNA-seq.sorted.bam[bam_header_read] EOF marker is
absent. The input is probably truncated.
_EGAR00001124500_RNA-seq_PAIRED_ICGC_PA103_s_120626_3a.sorted.bam[bam_header_read]
EOF marker is absent. The input is probably truncated.
_EGAR00001352529_RNAseq_paired-end_ICGC_MB206_s_130705_8.sorted.bam[bam_header_read]
EOF marker is absent. The input is probably truncated.

**Comment by rcurrie** [comment]
@hbeale does this still need to happen or is it old news?
