### ISSUE TITLE
Repository - phs000709.v1.p1 fibrolamellar hepatocellular carcinoma

### ISSUE THREAD

**Issue by klearned** [UCSC-Treehouse/operations#24]
Original paper: [PMC4286414](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4286414/)
From: dbGap [phs000709.v1.p1](http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000709.v1.p1)
Detailed file spreadsheet: [EGAD00001001666 LGG Epilepsy Cohort RNA-Seq](https://docs.google.com/a/ucsc.edu/spreadsheets/d/1osCWejRdOZ6hYgK7olC9qDSKHpTbBz7Q2lkL8hoiQeE/edit?usp=sharing)

Note, these data are **paired-end**

**Task List:**
- [x] Request permission
- [x] Download data
- [x] Convert .sra to fastq
- [x] Treeshop (RNAseq Pipeline + QC)

Can't find any clinical data. I found this table in one of the papers, but it doesn't really seem to match up with the data: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4359253/table/T1/

**Paper Excerpts**

> **Abstract**
>
>Fibrolamellar hepatocellular carcinoma (FL-HCC) is a rare liver tumor affecting adolescents and young adults who have no history of primary liver disease or cirrhosis. We performed RNA sequencing on FL-HCC tumors and identified a chimeric transcript that was expressed in all tumor samples but not in adjacent normal liver. The chimeric RNA was confirmed by RT-PCR and Sanger Sequencing. Based on the results of whole genome sequencing, the chimeric transcript is the result of a ~400 kilobase deletion on chromosome 19. The chimera was predicted to code for a protein with the amino-terminal domain of DNAJB1, a homolog of the molecular chaperone DNAJ, fused in frame with PRKACA, the catalytic domain of protein kinase A. The presence of this chimera protein was established by immunoprecipitation and Western Blot analysis. Expression of the chimera in human cell culture demonstrates that it retains kinase activity. Evidence for a DNAJB1-PRKACA chimeric transcript in 15 out of 15 FL-HCC patients suggests that it contributes to tumor pathogenesis.

> **RNA-sequencing**
>RNA-seq libraries were generated using the TruSeq total stranded RNA-seq kit with Ribo-Zero ribosomal RNA depletion (Illumina, San Diego, CA) following manufacturer’s instructions. Libraries were sequenced with 2x50bp paired-end reads on an Illumina HiSeq 2500 in high-output mode to an average depth of 86x106 paired-end reads/sample, with a range of 43x106-139x106. We mapped reads to the human reference genome (GRCh37) using the STAR aligner (1), and quantified read counts for all genes annotated in Gencode v16 (GRCh37) with HTSeq-count, version 0.5.3p9 (2). 
>
>Differential gene expression analysis was performed with the Bioconductor package DESeq2 (3).   Differential exon usage was assessed with DEXSeq (4) using ENSEMBL gene annotations (GRCh37, release 73). Candidate fusion transcripts were generated with FusionCatcher (v99) (5). Sashimi plots were prepared with the MISO package (6).

**Comment by klearned** [comment]
**Issues:**
I downloaded phs000709.v1.p1, Fibrolamellar Hepatocellular Carcinoma, using prefetch and all the .sra files validated fine with the vdb-validate tool. However, converting to fastqs using fast-dump has indicated a couple issues:

1) For each of the 29 files, fastq-dump gave multiple warnings about three columns not being found, LABEL, LABEL_START, and LABEL_LEN. Does this indicate an issue with the data (see below for the actual warnings)?

2) Additionally, 12 of the 29 files also gave an error about a certain number of reads being rejected because READLEN < 1. When I compare the number of lines in the end1 and end2 of the resulting fastq files (I have fastq-dump splitting into two files), they don't have the same number of lines. The files without this error do have the same number of lines.

Here is the output from an SRR with both issue described above:

```
Rejected 309270 READS because READLEN < 1
Read 44407458 spots for /scratch/klearned/dbGap/ncbi/dbGap-11732/sra/SRR1267599.sra
Written 44407458 spots for /scratch/klearned/dbGap/ncbi/dbGap-11732/sra/SRR1267599.sra
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_START
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_LEN
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_START
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_LEN
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_START
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_LEN
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_START
2016-11-27T16:25:13 fastq-dump.2.7 warn: column not found while opening table within short read archive module - column LABEL_LEN
2016-11-27T16:51:35 fastq-dump.2.7 info: /scratch/klearned/dbGap/ncbi/dbGap-11732/sra/SRR1267599.sra 44407458 spots
```

**Comment by klearned** [comment]
When I sent in a question to the SRA helpdesk regarding the second issue described above (READLEN <1), SRA helpdesk replied with this:

> Note that the ' READLEN < 1 ' message is not an error but just informational and does not indicate an issue. Data submitted as paired-end may not always have both mate pairs for each spot (due to quality filtering, alignment issues, etc.) and in these cases the missing read is created as 0-length, resulting in this message upon dumping. This is also why there are different numbers of reads in the forward/reverse fastq files, it generally indicates the data were submitted this way.

Cameron ran one that had the READLEN <1 issue through treeshop, this one:

`SRR1267597      /scratch/klearned/dbGap/phs000709.v1.p1/data/fastq/SRR1267597_1.fastq.gz,/scratch/klearned/dbGap/phs000709.v1.p1/data/fastq/SRR1267597_2.fastq.gz`

...but it crashed Treeshop, when it failed in Toil. He then tried to run it through the old pipelines manually and it failed in Toil again, so there is neither RNASeq nor QC output.

**Comment by klearned** [comment]
Should we try to run them all through Treeshop, or just try to run those that didn't have any reads with READLEN <1 ?

**Comment by klearned** [comment]
This  dataset **phs000709.v1.p1** is ready to run through just those samples that didn't have any READLEN <1 rejected issues through Treeshop (RNAseq + QC).
n=17 samples (from 6 patients)

**Please place output folders here:**
`/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000709.v1.p1_fibrolamellarHepatocellularCarcinoma`

**Manifest**
`/pod/pstore/groups/treehouse/published-data/dbGap/phs000709.v1.p1/fastq/phys000709manifest`

**Comment by rcurrie** [comment]
Running...

**Comment by rcurrie** [comment]
14 of 17 complete, and ALL HAVE PASSED!

**Comment by rcurrie** [comment]
All 17 complete:
@hbeale 14 PASSED, 3 generated a 0 length bam (03, 17, and 18)

@klearned Following protocol all 17 should be imported into MedBook for compendium, passing back to Katrina though for further routing (holly or ellen)

**Comment by klearned** [comment]
@rcurrie Great!! My best pass record yet! I'll take it to the next step.

@adurbin2 Have you imported these into your index yet?

On Dec 15, 2016 8:56 AM, "Rob Currie" <notifications@github.com> wrote:

Assigned #24 <https://github.com/UCSC-Treehouse/operations/issues/24> to
@klearned <https://github.com/klearned>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/UCSC-Treehouse/operations/issues/24#event-895520521>,
or mute the thread

**Comment by klearned** [comment]
@e-t-k  Please import TPM values for all 17 samples into MedBook for addition to Compendium V3. Thanks!

`/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000709.v1.p1_fibrolamellarHepatocellularCarcinoma`

Please let me know if you need additional information.

**Comment by adurbin2** [comment]
Will do - need to grab the output folders & bams paths to the worksheet, then I will bring in everything at once. Way to go!

**Comment by adurbin2** [comment]
I'm confused about the status of bam files. Holly mentioned just now that we want to save the QC-putput bams and not the RNA-seq process bams; but she also mentioned that Rob had set bams (not sure which) to not be saved. And that it's different for prospective samples vs repository samples.... This is not something I had heard before. @rc if bams are required, is it too late for us to grab whatever bams are deemed necessary for this repository dataset?

**Comment by klearned** [comment]
Actually, @adurbin2 and @e-t-k , which go into medbook? All or just the tumor samples. There are some normals included in this dataset so I am wondering if those go into medbook because I know they don't go into V3.

**Comment by e-t-k** [comment]
@klearned MedBook is for samples that are going to be used in further downstream analysis. So the question to ask is "What are we going to use these normal samples for?" -- and I don't know the answer to this.

In any case, the normals -- if they are going to MedBook at all -- should be in a different Data Set from the tumor samples.

How can I determine which samples are tumor and which are normals?

**Comment by klearned** [comment]
Thanks @e-t-k , I am keeping all the info about the data in this [spreadsheet](https://docs.google.com/a/ucsc.edu/spreadsheets/d/1osCWejRdOZ6hYgK7olC9qDSKHpTbBz7Q2lkL8hoiQeE/edit?usp=sharing) (I am trying to provide the link to my spreadsheet in the ticket description) these samples are the normals:
SRR1267605
SRR1267607
SRR1267614
SRR1267616
SRR1267618

The rest are tumor (subcategorized as mets, tumor, recurrence):
**Metastasis**:
SRR1267601
SRR1267602
SRR1267604
SRR1267606
SRR1267609
SRR1267610
SRR1267622

**Tumor**:
SRR1267603
SRR1267608
SRR1267613
SRR1267615

**Recurrence**:
SRR1267617

Some of these are from the same individual (e.g. a normal, tumor and met form the same patient) Do you need to know which are from the same patient?

**Comment by klearned** [comment]
Actually, @e-t-k , what information about the data gets ported into medbook and where do you usually pull it from?

**Comment by e-t-k** [comment]
> Do you need to know which are from the same patient? 
> what information about the data gets ported into medbook and where do you usually pull it from?

The bare minimum I need to import samples into MedBook is 
* what to name the data set and study
* the list of  RNA-Seq output file locations for the samples to import.
Then, the sample files contain the sample IDs and expression values. 

If the samples IDs should be  different from what is in the output files, I need a mapping of "correct IDs" to "IDs in the files".

Next, optionally, we might have metadata about the samples so that we can search / filter on them in a useful fashion.
The metadata is imported separately as a "clinical form" -- a TSV file that references the sample IDs as MedBook knows them and has whatever md information that is available.

**Comment by klearned** [comment]
@e-t-k  OK, thanks for this info!

**Comment by adurbin2** [comment]
So, when we do push the button to create v3, I expect to provide one worksheet containing the metadata (disease, stage, grade, age, gender... all of the essential fields, matched by sample id) to match all the samples on the Medbook list that Ellen will produce. That's one reason why we need a unique ID for each incoming RNASeq sample, and why I collect the clinical metadata from the papers, along with output folder locations.

**Comment by e-t-k** [comment]
- TPM files rsem.genes.tpm.hugo.tab created for each of these 17 samples and placed in the Hugo dir.

@adurbin2  Please let me know which of these samples should be uploaded to MedBook and  whether they need to go into multiple data sets.

**Comment by adurbin2** [comment]
Of the 17 samples, twelve samples are from tumor and we expect to include them in the next compendium:
SRR1267601
SRR1267602
SRR1267603
SRR1267604
SRR1267606
SRR1267608
SRR1267609
SRR1267610
SRR1267613
SRR1267615
SRR1267617
SRR1267622

Five are from normal tissue (will not be used to build compendia, but may be useful to Treehouse in other ways):
SRR1267605
SRR1267607
SRR1267614
SRR1267616
SRR1267618

Uploading them as two sets makes sense to me.

**Comment by e-t-k** [comment]
### MedBook Import
17 samples will be imported to MedBook with TPM normalization.

#### Study 
"phs000709.v1.p1 fibrolamellar hepatocellular carcinoma"  
namespace: *phs000709/*

#### Data Sets
"phs000709.v1.p1 fibrolamellar hepatocellular carcinoma - TUMOR (TPM)"
"phs000709.v1.p1 fibrolamellar hepatocellular carcinoma - NORMAL (TPM)"

**Comment by e-t-k** [comment]
All samples imported to MedBook. [Normal dataset](https://medbook.io/manage/data-sets/9FhGzWr6vhu7AB9K6) [Tumor dataset](https://medbook.io/manage/data-sets/YfGNqqMqvcNqF4Zvz)

**Comment by klearned** [comment]
See #32 for running of the 12 samples that were originally excluded due to READLEN errors.
