### ISSUE TITLE
Construct Compendium v2 TPM expression data file

### ISSUE THREAD

**Issue by e-t-k** [UCSC-Treehouse/operations#25]
Per meeting yesterday, we're constructing a file consisting of the expression data for tumormap compendium v2, using the TPM unit of measurement instead of "norm counts". @hbeale my understanding is that you have this data already compiled and we just have to pin down the file formatting?

My 1 big question is whether to apply **log2(n+1)** scaling or not, since it is actually optional in MedBook. I think the answer is yes.

### Format

A plain text tab-separated file.
 - item (0,0) is the string "gene_id".
 - Sample IDs are   ~~MedBook fully qualified with study prefix~~ the bare sample IDs as received from the RNA-Seq pipeline. Eg: "TH01_234_567"

| gene_id | *Sample Id1* | *Sample Id2* | ...  |
|---|---|---|---|
| *Feature Id 1*  | 0.0  | 1.23  | ...  |   
| *Feature Id 2*  |  7.89 | 4.56  | ...  |   
| ...  | ...  | ...  | ...  |   

### Features
* Features are converted to Hugo Gene Names from the ensembl IDs. ~~Feature names **may be non-unique** (multiple lines with the same feature ID).~~ (This will drop some (50?) lines from the original TPM file - ensembl IDs that don't have associated Hugo names.)
* ETA Dec 19 : @hbeale has agreed to provide unique feature names. Expression values from duplicate feature IDs are averaged together.

### Samples
Samples are in two separate files:
* All TCGA/TARGET samples from v2 (includes the new AMLs)
* All other samples from v2

### Data Entries

 Data is from the TPM column of *rsem_genes.results*

Data is normalized with log<sub>2</sub>(*n*+1) from the original values.

~~Question: Should it have **log2(n+1)** normalization applied to it? By custom, we perform this scaling on all samples imported into MedBook, but it is optional. Glancing at the TPM for an arbitrary sample I do see counts as high as 20k (compared to 500k for norm_counts). This leads me to believe that the normalization *should* be applied.~~

### Where

I've made the following folder to store these output files:
*/pod/pstore/groups/treehouse/backed_up/compendium*

### Changes from the above

 - Sample IDs are MedBook fully qualified with study prefix, as they came out of the downloaded compendium. Eg: "ckcc/TH01_234_567"
- ~~Feature IDs are fully unique (will result in fewer lines). Expression values from duplicate feature IDs are averaged together.~~ ETA - Dec 19 - @hbeale has provided unique feature IDs.

- Per #7, 3 samples will be removed due to poor QC results:
  * ckcc/TH05_0109_S01_RNASeq
  * ckcc/TH05_0110_S01_RNASeq
  * ckcc/TH05_0111_S01_RNASeq

- Note that per #9 , 6 samples that were included in the norm_counts v2 compendium are not present in the TPM v2 compendium as delivered by @hbeale and cannot be recovered.
icgc/EGAR00001077871
icgc/EGAR00001077872
icgc/EGAR00001077873
icgc/EGAR00001077874
icgc/EGAR00001077875
icgc/EGAR00001077876

- If I receive info on further samples to be removed, I'll document those here as well.

**Comment by hbeale** [comment]
Hi Ellen--

Thanks for the detail. For feature IDs it is really helpful for biological interpretation by a human when the Hugo ID is used, even though it's computationally imperfect. I assume that conversion should happen outside Medbook, but I could be convinced otherwise. What are your thoughts? 

I can construct separate files as you request. I am selecting TCGA target samples based on the compendium v2 URL that you gave me and Meghan. Will that contain the new AMLs? If not, please send me the IDs I would see in the TPM data I downloaded via Xena (this dataset; I exclude all samples not part of compendium v2.

**Comment by e-t-k** [comment]
> For feature IDs it is really helpful for biological interpretation by a human when the Hugo ID is used, even though it's computationally imperfect.

You're right & I've updated the original issue. I had thought translating to hugo would be prohibitively inconvenient but i had forgotten the discussion we had and that the mapping is easy to retrieve from any existing hugo output file.

> I am selecting TCGA target samples based on the compendium v2 URL that you gave me and Meghan. Will that contain the new AMLs?

Yes, it will. There should be 10,531 TCGA/TARGET samples in total.  Here's the 2 lists of sample IDs for double-checking purposes.

[compendium.v2.tcga_target.txt](https://github.com/UCSC-Treehouse/operations/files/649877/compendium.v2.tcga_target.txt)
[compendium.v2.all_other_samples.txt](https://github.com/UCSC-Treehouse/operations/files/649876/compendium.v2.all_other_samples.txt)

**Comment by hbeale** [comment]
Thank you; I've reconciled the sample IDs. 

Yes, log2(tpm+1) scaling should be applied. Do you want me to pre-scale the input data I'm preparing or no?

**Comment by e-t-k** [comment]
> Do you want me to pre-scale the input data I'm preparing or no? 

Please pre-scale it, since I'm not importing it into MedBook in the immediate future.

Incidentally -- so we're using TPM for the V3 compendium -- do you know if Yulia is expecting this,  or if I'm also delivering a parallel norm_counts v3 compendium?

**Comment by hbeale** [comment]
Olena and I discussed this and we're converting everything to TPM, so you will not need to deliver a parallel norm_counts v3 compendium.

**Comment by hbeale** [comment]
@e-t-k , I realized that my process doesn't include the collapsing process that I believe medbook does (e.g. when the same gene name appears more than once, they are reported as a single gene with the averaged value). What do you think we should do about that?

**Comment by e-t-k** [comment]
@hbeale I've update the original comment per our chat just now & separated it into your & my deliverables. Please let me know if I missed anything.

**Comment by hbeale** [comment]
The compressed, tab delimited files 

compendiumV2TPM.log2Plus1.Hugo.noDupeRowOrCol.2016.12.16_15.40.26.Treehouse.txt.gz and 
compendiumV2TPM.log2Plus1.Hugo.noDupeRowOrCol.2016.12.16_15.40.26.TCGA.TARGET.txt.gz

have been copied to /pod/pstore/groups/treehouse/backed_up/compendium/TPM/. They contain log2(tpm+1) data obtained from Xena and RNA-Seq output files. Gene IDs were converted to Hugo; the 50 non-convertible genes were dropped. Remaining duplicate Gene IDs were averaged. The Xena data contained several duplicate samples. I was told that these samples contain different aliquots from the same sample; those values were merged. 

All data related to this build of the compendium is designated compendiumV2TPM.log2Plus1.Hugo.noDupeRowOrCol.2016.12.16_15.40.26.

Any subsequent updates will change the date and possibly the text. 

I believe my deliverable on this issue is complete -- please let me know if not.

**Comment by e-t-k** [comment]
- [x] remove 3 samples from Treehouse compendium file: TH05_0109_S01_RNASeq, TH05_0110_S01_RNASeq, TH05_0111_S01_RNASeq
output: `compendiumV2TPM.log2Plus1.Hugo.noDupeRowOrCol.2016.12.16_15.40.26.Treehouse.removed3samples.txt`

- [ ] apply fully qualified study IDs to Treehouse compendium file
- [ ] apply fully qualified study IDs to TCGA/TARGET compendium file

**Comment by e-t-k** [comment]
TPM Compendium 2 files have been created.
They both have full MedBook sample names.
3 samples listed above have been removed from the Treehouse compendium file.

Next step:

- [X] retrieve preliminary compendium v3 additional samples from MedBook
output: `compendiumV3TPM.fromMedbook.2016.12.19.txt`
- [ ] re-order genes from this file to match the order for files above (in a reproducible way)
- [ ] aggregate all files to produce draft compendium 3

**Comment by e-t-k** [comment]
Also, Add patient1 to the compendium. This needs to be done before the steps above.

- [ ] create hugo tpm file
- [ ] import to medbook
- [ ] create new v3 sample group including patient1
- [ ] export

**Comment by e-t-k** [comment]
### expression and variance filters.

The expression and variance filtering scripts were applied to the draft compendium 3. 

#### Scripts
`python2.7 filter_out_genes_unexpressed_in_most_samples.py --in_file compendiumV3TPM.log2Plus1.Hugo.noDupeRowOrCol.FullMBHeader.2016.12.20.FULL.txt --proportion_unexpressed 0.8 --out_file full.v3.expressionfiltered.12.21.tsv`
`python2.7 filter_out_lowest_varying_genes.py  --in_file full.v3.expressionfiltered.12.21.tsv --filter_level .2 --out_file full.v3.var_and_expressionfiltered.12.21.tsv`

#### NOTE ON EXPRESSION FILTERING -- SCRIPT WAS ALTERED
Original expression filtering script ( *filter_out_genes_unexpressed_in_most_samples.py* ) removed no features (expected = about half). Per discussion with @hbeale , this was due to rounding issues, details below. Script was changed so that instead of filtering features with 80+% expression = 0, it filtered 80+% expression less than 0.00014425:
`      line_zeros = [i for i in line_float if i == 0.0]`
changed to
`      line_zeros = [i for i in line_float if i <= 0.00014425]`

This resulted in a reasonable proportion (42%) of features dropped.

##### details / math

@hbeale 's note on downloading TPM samples from Xena:

* Downloading tpm from xena; it’s log<sub>2</sub>(tpm+0.001) transformed. If I untransform it ((2<sup>x</sup>)-0.001), some values are less than 0 because of rounding, so instead I untransform it using ((2<sup>x</sup>)-0.0009)

So. Given a value that was originally 0, the un-and retransformation would be normally be calculated to take it back to 0; but instead it's transformed to a slightly different number:

`log`<sub>`2`</sub>`(0+0.001) = -9.96578428...`
`((2`<sup>`-9.965...`</sup>`)-0.0009) = 0.0001`
So 0 un-transforms to 0.0001.
Then, we apply our own log<sub>2</sub>(n+1) scaling:
`log`<sub>`2`</sub>`(0.0001+1) = 0.0001442...`

And we result in a .0001442 value instead of 0.

Python and wolfram alpha say this value is 0.0001442622910945383 ; the value found in the expression data is instead 0.000144246577413644. I consider this "close enough" and will track down the difference if and when it's deemed necessary.

**Comment by hbeale** [comment]
@e-t-k works for me. Thanks for the detail!

**Comment by e-t-k** [comment]
Note : For metadata compendium file, linux line endings (not dos) are required

**Comment by adurbin2** [comment]
@hbeale @e-t-k is this issue completed? OK to close the ticket if it's over --
