### ISSUE TITLE
TPM with Hugo IDs on future processed data

### ISSUE THREAD

**Issue by hbeale** [UCSC-Treehouse/operations#26]
We either need to add a conversion of ensembl ids to hugo ids to the rna-seq pipeline, or convert them separately. 

For our future reference, the details of conversion are here:
https://www.synapse.org/#!Synapse:syn6041633/wiki/410931

**Comment by rcurrie** [comment]
Should we stick with ensembl (or entrez) to retain isoform information for down the road? isoforms?  Suggest maybe post v3 we have a more general discussion about this - also suggest bringing this subject up today at cancercats with the xena team if relevant.

@e-t-k jvivian's conversion code uses python pandas and is here:

https://github.com/jvivian/docker_tools/blob/master/gencode_hugo_mapping/gencode_hugo_map.py

There is a python package from ensembl that's a bit more general I used for the CGT search where I had to go from coordinates to HUGO and therefore deal with hg37/38.... Details are here:

https://github.com/rcurrie/search-cgt/blob/master/searchcgt/annotate.py

**Comment by e-t-k** [comment]
For the short term, I've set up some scripts for manual conversion, using the empirical mapping file that @hbeale generated:

https://github.com/UCSC-MedBook/data-wrangling-scripts/tree/master/TPM_import

**Comment by hbeale** [comment]
Good call @e-t-k . Thank you!

**Comment by e-t-k** [comment]
Next I plan to update my scripts to place the TPM samples in the RSEM/Hugo output directories as if they were there all along.

Filename will be : `$samplename/rnaseq/RSEM/Hugo/rsem.genes.tpm.hugo.tab`

@rcurrie , it would be convenient if you could set up your umask so these output directories will be g+w by default; alternatively, I'll just mount them in a Docker and chmod them myself when necessary.

**Comment by e-t-k** [comment]
TPM samples can now be placed in the Hugo output directories. See Step 5 of the [TPM readme](
https://github.com/UCSC-MedBook/data-wrangling-scripts/blob/master/TPM_import/README.md#how-to-transform-tpm-data-using-these-scripts) for usage.
