### ISSUE TITLE
run tertiary analysis on C021_0006_batch1 for precision analysis

### ISSUE THREAD

**Issue by hbeale** [UCSC-Treehouse/operations#40]
copied 18 files into 
backups_jupyterhub/for_jupyter/C021_0006_batch1_toe_40_2017-03-20

file names
C021_0006_batch1_est10M
C021_0006_batch1_est12M
C021_0006_batch1_est14M
C021_0006_batch1_est16M
C021_0006_batch1_est18M
C021_0006_batch1_est1M
C021_0006_batch1_est20M
C021_0006_batch1_est25M
C021_0006_batch1_est2M
C021_0006_batch1_est30M
C021_0006_batch1_est35M
C021_0006_batch1_est3M
C021_0006_batch1_est40M
C021_0006_batch1_est45M
C021_0006_batch1_est4M
C021_0006_batch1_est50M
C021_0006_batch1_est6M
C021_0006_batch1_est8M

**Comment by e-t-k** [comment]
Tumormap running in Jupyter. 
With this number of samples though I probably ought to run it manually so I can keep an eye on it.
Will rerun manually if it hasn't finished in half an hour, which is probably extremely optimistic.

**Comment by e-t-k** [comment]
@hbeale run complete.
Results folder within my Jupyter hub: `outlier_data/results/C021_0006_batch1_toe_40_2017-03-20/`
Working folder: `archived_outlier_analysis_runs/C021_0006_batch1_toe_40_2017-03-20`

If you need me to deliver you the results, I can do that as well.

**Comment by hbeale** [comment]
Thanks!! Can I get the tumor map results too? Or are they there and I missed them?

**Comment by e-t-k** [comment]
@hbeale I'll run them real quick.
In the meantime, so I can add it to the standard path, what info from the "results" do you need?
- [ ] neighbors and similarity scores
- [ ] bookmark to tumormap graphic
- [ ] clinical information
- [ ] something else?

**Comment by hbeale** [comment]
Awesome. I think in the future all three; I can't think of anything else. Basically, the info we used to get in a text file from Theresa.

**Comment by e-t-k** [comment]
@hbeale ran reports and emailed to you.
And yes, the text file from teresa is  a separate step which aren't replicated by the API.

|  | API | manual run | additional manual 'report' run |
|-|-|-|-|
|Neighbor Sample IDs| √ | √ |  |
|Similarity Score| √ | √ |  |
|Bookmark to Tumormap| √ |    | √ |
|Clinical Details|   |  |√  |
