### ISSUE TITLE
Process batch #84 manually

### ISSUE THREAD

**Issue by rcurrie** [UCSC-Treehouse/operations#9]
repository-datasets-rnaseq-20161004
[manifest84.txt](https://github.com/UCSC-Treehouse/operations/files/514707/manifest84.txt)

**Comment by rcurrie** [comment]
@hbeale is it ok to rename all to EGZxxxxxx_R1.fastq.gz, for example:

_EGAZ00001000235_81MK3ABXX_6_withJunctionsOnGenome_dupsFlagged.R1.fastq.gz     
-> EGAZ00001000235_RNASeq_R1.fastq.gz

_EGAR00001077871_RNA-Seq_tumor_4116738_RNA.sorted.ubu2.fastq_pairs_R1.fq.gz
-> EGAR00001077871_R1.fastq.gz

Or are all the various comments post EGAxxxx important? Seems like they should really be in the meta.

**Comment by hbeale** [comment]
agreed -- the various comments post EGAxxxx should be meta. I don't think
they need to be in the file name. If you make a note of the renames here, I
think that will be sufficient insurance.
tnx

**Comment by rcurrie** [comment]
@cygao go ahead and start processing as currently named

**Comment by cygao** [comment]
I have begun processing with file names intact

**Comment by rcurrie** [comment]
Sorry, pause, Holly wants to change the names. She's going to do so and then I'll copy back to pipeline0 and we can start again, sorry.

**Comment by rcurrie** [comment]
I deleted them all from pipeline0/intake. If you moved any to the other machines delete and we'll start again once the newly named files are ready.

**Comment by cygao** [comment]
Got it, I am awaiting newly renamed files

**Comment by rcurrie** [comment]
Files renamed by Holly on pod, copied to pipeline0/intake for processing as below. @cygao go ahead and start processing. If you have some done and want them moved back to pod before they are all done just pass this to me and I'll empty /outputs.

/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000158/fastq/EGAZ00001000235.R1.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000158/fastq/EGAZ00001000235.R2.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077871_R1.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077871_R2.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077872_R1.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077872_R2.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077873_R1.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077873_R2.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077874_R1.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077874_R2.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077875_R1.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077875_R2.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077876_R1.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281/fastq/EGAR00001077876_R2.fq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076555.R1.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076555.R2.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076556.R1.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076556.R2.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076557.R1.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076557.R2.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076558.R1.fastq.gz
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000356/fastq/EGAR00001076558.R2.fastq.gz

**Comment by cygao** [comment]
@hbeale Some files are named *.R1 and others _R1 (like past samples). Which naming convention should be used in the future?

**Comment by cygao** [comment]
EGAD 55 -72 (6 total) are currently running across all pipelines.

**Comment by cygao** [comment]
Multiple pipelines are giving errors such as

> Read HWI-ST751:96:D07KCACXX:5:1101:12154:2775 is both unalignable and alignable

@rcurrie please advise

**Comment by rcurrie** [comment]
Save the logs of the errors noting which file threw it, kill the job, and move on to another. File the name of the file and the error log here and put an @hbeale for Holly to take a look at the input file.

**Comment by cygao** [comment]
pipeline0 and 1 have failed. I will investigate and restart

**Comment by hbeale** [comment]
I've never  seen that error before. Troubleshooting ahead.

**Comment by cygao** [comment]
I am hypothesizing that any files need to be renamed _R* instead of .R*. I will rename and rerun the samples and see what happens.

**Comment by rcurrie** [comment]
Try _R* and make sure there are no periods before the _R*

(The fix to all that is in the 2.0.10 or greater I believe but the docker hasn't been vetted yet)

**Comment by cygao** [comment]
I have replaced the periods with underscores, but the same error is returned

> ubuntu@pipeline0:/mnt/pipelines/rnaseq-cgl-pipeline/samples$ tar -tf EGAR00001076555.tar 
>EGAR00001076555_R1.fastq.gz
>EGAR00001076555_R2.fastq.gz

**Comment by hbeale** [comment]
EGAR00001076555 is a lost cause for compendium freeze version 2. The same read ID has multiple entries in the fastq input. We need to revisit conversion from bam to fastq. We will try to do this before the processing freeze for version 3. Please let me know about any other samples you have with similar errors and I will examine them.

**Comment by cygao** [comment]
@hbeale Could you please check the following files?

> EGAR00001076556

> EGAR00001076557
> EGAR00001076558

> EGAZ00001000235

**Comment by hbeale** [comment]
Sadly, I found problems with EGAR00001076556, EGAR00001076557, EGAR00001076558 as well as the previously reported EGAR00001076555. I did not see obvious problems in the first 40 lines of EGAZ00001000235; if it fails, please record the error and send it to me. An example of an informative error is "Read HWI-ST751:96:D07KCACXX:5:1101:12154:2775 is both unalignable and alignable".

**Comment by cygao** [comment]
All samples (except the 4 with errors) are currently being run.

**Comment by hbeale** [comment]
Hi folks. Can I get an update before 8am tomorrow? Thanks.

**Comment by cygao** [comment]
All good files have been completed and seem to be quality. I will copy over to pipeline0 once I get off class (5pm)

**Comment by cygao** [comment]
Samples are writing to medbook

@rcurrie Please close issue once outputs are copied off.

**Comment by rcurrie** [comment]
Copying outputs back to pod into published-data/ICGC_Sep2016/Batch84

@hbeale I'll then move into the respective study locations unless you'd prefer to look at them in one place first

**Comment by rcurrie** [comment]
Copied to pod, ok to remove from pipeline

@cygao note there is a few stray bams in outputs:
-r--r--r--  1 rcurrie treehouse  9615183805 Oct 11 18:33 EGAR00001076555.sorted.bam
-r--r--r--  1 rcurrie treehouse  8834644739 Oct 11 18:42 EGAR00001076556.sorted.bam
-r--r--r--  1 rcurrie treehouse 11087230311 Oct 11 18:52 EGAR00001076557.sorted.bam
-r--r--r--  1 rcurrie treehouse 10084406272 Oct 11 19:02 EGAR00001076558.sorted.bam
-r--r--r--  1 rcurrie treehouse 12735889274 Oct 11 19:14 EGAR00001077871.sorted.bam

**Comment by rcurrie** [comment]
in /pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/Batch84

-r--r--r--  1 rcurrie treehouse 12735889274 Oct 11 19:14 EGAR00001077871.sorted.bam
-rw-r--r--  1 rcurrie treehouse   105417282 Oct 11 20:30 EGAR00001077871.tar.gz
-r--r--r--  1 rcurrie treehouse  8274608990 Oct 11 19:22 EGAR00001077872.sorted.bam
-rw-r--r--  1 rcurrie treehouse    94085665 Oct 11 20:30 EGAR00001077872.tar.gz
-r--r--r--  1 rcurrie treehouse 12363234486 Oct 11 19:34 EGAR00001077873.sorted.bam
-rw-r--r--  1 rcurrie treehouse   104341254 Oct 11 20:30 EGAR00001077873.tar.gz
-r--r--r--  1 rcurrie treehouse 12672135135 Oct 11 19:46 EGAR00001077874.sorted.bam
-rw-r--r--  1 rcurrie treehouse    99818741 Oct 11 20:30 EGAR00001077874.tar.gz
-r--r--r--  1 rcurrie treehouse 14446111501 Oct 11 19:59 EGAR00001077875.sorted.bam
-rw-r--r--  1 rcurrie treehouse    97828472 Oct 11 20:30 EGAR00001077875.tar.gz
-r--r--r--  1 rcurrie treehouse 14199803108 Oct 11 20:13 EGAR00001077876.sorted.bam
-rw-r--r--  1 rcurrie treehouse   101266900 Oct 11 20:31 EGAR00001077876.tar.gz
-r--r--r--  1 rcurrie treehouse 15634434677 Oct 11 20:28 EGAZ00001000235.sorted.bam
-rw-r--r--  1 rcurrie treehouse    99692210 Oct 11 20:31 EGAZ00001000235.tar.gz

**Comment by e-t-k** [comment]
I am removing the following samples have been removed from the ckcc Data Set/ Study.
When done, please re-upload using the icgc study and EGAD-named data sets as listed in manifest84.txt in the first comment.

[X] ckcc/EGAR00001077872
[ ] ckcc/EGAR00001077871
[ ]ckcc/EGAR00001077876
[ ] ckcc/EGAR00001077873
[ ] ckcc/EGAR00001077874
[ ]ckcc/EGAZ00001000235
[ ]ckcc/EGAR00001077875

**Comment by rcurrie** [comment]
I've moved the bam and tar.gz into the appropriate study folder on pod:
EGAR00001077871, EGAR00001077872, EGAR00001077873, EGAR00001077874, EGAR00001077875, EGAR00001077876 -> EGAD00001000281/bam & fastq

EGAZ00001000235 -> EGAD00001000158/bam & fastq

**Comment by cygao** [comment]
Samples have been uploaded to correct ICGC location, currently writing. I will close issue once all are successfully written.

**Comment by adurbin2** [comment]
Hi guys, Ellen and I have been searching for these, and cannot locate. Can you provide the full path to the output folders in particular?
EGAR00001077871, EGAR00001077872, EGAR00001077873, EGAR00001077874, EGAR00001077875, EGAR00001077876 from the 281 study

and EGAZ00001000235 from the 000158 study

**Comment by e-t-k** [comment]
@rcurrie in particular, I can't find any of the .tar.gz output. I found one sample but that's it.

`/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000158/fastq/EGAZ00001000235.tar.gz`

**Comment by rcurrie** [comment]
I remember moving them as per above such that they were all under the specified folders:

EGAR00001077871, EGAR00001077872, EGAR00001077873, EGAR00001077874, EGAR00001077875, EGAR00001077876 -> EGAD00001000281/bam & fastq

EGAZ00001000235 -> EGAD00001000158/bam & fastq

It looks like i moved them into respective folders under EGAD00001000158 and EGAD00001000281

But now there is only:

./ICGC_Sep2016/EGAD00001000158/fastq/EGAZ00001000235.tar.gz

As I vaguely recall this was part of the confusion around the names on theses - the originals had super long things with logs of magic. I suggested just leaving them as they could be considered ‘UUID’s. I think Holly went in and changed a bunch.

Holly - any reccolection?

**Comment by rcurrie** [comment]
@hbeale any recollection of the renaming of these and/or moving them?

**Comment by hbeale** [comment]
I have no explicit recollection of this. My suggestion is to figure out what the actual fastq files were named (revisiting EGA if needed) and then search the pod treehouse directory on that name. I tried that for one sample (below) and didn't find any output. I conclude there is no output for this sample in /pod/pstore/groups/treehouse/.

cd /pod/pstore/groups/treehouse/
find . -iname "*EGAR00001077871*tar" # no hits for tar output
find . -iname "*EGAR00001077871*" -type d # no hits for untarred dir output
find . -iname "*EGAR00001077871*.xml" -exec grep filename {} \; # RNA-Seq_tumor_4116738_RNA
find . -iname "*RNA-Seq_tumor_4116738_RNA*tar" # no hits
find . -iname "*4116738*tar" # no hits for tar output
find . -iname "*4116738*" -type d # no hits for untarred dir output

**Comment by adurbin2** [comment]
We've not been able to locate bam files or output folders for these six files (see notes above). @rcurrie Can we re-run their fastqs through RNASeq to generate bams & output folders? I have attached a manifest. Please save the bam and output files to a temporary folder, and advise when I can copy them to their destination on pod. 

icgc/EGAR00001077871	
icgc/EGAR00001077872	
icgc/EGAR00001077873	
icgc/EGAR00001077874	
icgc/EGAR00001077875	
icgc/EGAR00001077876	

[batch84_redo_manifest_RNASeq.txt](https://github.com/UCSC-Treehouse/operations/files/646556/batch84_redo_manifest_RNASeq.txt)

**Comment by rcurrie** [comment]
I can run these easily but the manifest isn't valid. See:

/pod/pstore/groups/treehouse/backed_up/archive/output/externalSamples/phs000699.v1.p1_OSGenomics/phs000699RnaSeqManifest.tsv

for an example. Briefly:

- Header with "Submitter Sample ID" and "File Path"
- tsv format
- "Submitter Sample ID" can't have a slash (/) in the name as its used as a folder name (and also due to the following constraint)
- "Submitter Sample ID" must match the file name of the fastq pairs before the _1 or _R1 as that is the name the pipeline inserts into the RSEM file and which MedBook uses to name the sample when importing.

**Comment by adurbin2** [comment]
Well, then, please advise how to generate a tsv. I'm attaching the document saved from Excel as a txt file in tab-separated format - 
[batch84_redo_manifest_RNASeq2.txt](https://github.com/UCSC-Treehouse/operations/files/647168/batch84_redo_manifest_RNASeq2.txt)
let me know if that is not sufficient.

**Comment by rcurrie** [comment]
fastq's don't exists - folder referenced in each line is empty:
/pod/pstore/groups/treehouse/published-data/ICGC_Sep2016/EGAD00001000281

Wrt tsv its just a file ending in tsv with the fields separated by tabs

Excel exports a tsv but on the Mac apparently refuses to put the tsv ending. Also excel doesn't terminate lines correctly - if you look at the file you uploaded in the terminal or a text editor you'll see it all as one big line. That said I just modified treeshop to deal with this but we should try and generate valid tsv's - Google Sheets does it correctly. Unfortunately github refuses to attach a tsv. I'll try and enhance treeshop to deal with excel files directly...

**Comment by adurbin2** [comment]
Hm. I think I'll close the current issue and add the EGAD00001000281 repository back to @klearned Katrina's list, and we'll take this from the top.
